language: android
android:
  components:
    - build-tools-26.0.2
jdk: oraclejdk8
before_install:
 - git clone --depth=50 https://github.com/wala/WALA /tmp/WALA
install:
 - pushd /tmp/WALA
 - mvn clean install -DskipTests -B -q
 - popd
script:
 - mvn clean install -B
sudo: false
cache:
  directories:
    - $HOME/.m2
